#!/bin/bash

time=1
mem=$((500*1024*1024))
prog=/tests/data/a.out
count=1

# params
# $1 -> count
# $2 -> time limit in seconds
# $3 -> memory limit in seconds

if [ ! -z $1 ];then
    count=$1
fi
if [ ! -z $2 ];then
    time=$2
fi
if [ ! -z $3 ];then
    mem=$3
fi

for (( i=1; i<=$count; i++ ))
do
    runexec --timelimit $time --memlimit $mem --read-only-dir / \
        --output /tests/data/o${i}.txt --input /tests/data/in${i}.txt \
        $prog > /tests/data/stats${i}.txt
    sed -i "1,6d" /tests/data/o${i}.txt
    diff -tbB /tests/data/o${i}.txt /tests/data/out${i}.txt > /tests/data/diff${i}.txt
done